name: MySQL Workflow

on:
  push:
    branches:
      - main  # Configure aqui a branch em que deseja acionar o workflow

jobs:
  start-mysql:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Start MySQL Container
      run: |
        docker run -d \
          --name mysql-server \
          -e MYSQL_ROOT_PASSWORD=db-sef-password \
          -e MYSQL_USER=dafws \
          -e MYSQL_PASSWORD=7rVQW48ph2 \
          -e MYSQL_DATABASE=daf-ws \
          -e TZ=America/Sao_Paulo \
          -p 3306:3306 \
          mysql:8.0

  # test-mysql-connection:
  #   needs: start-mysql
  #   runs-on: ubuntu-latest

  #   steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Test MySQL Connection
      run: |
        # Aguarde alguns segundos para que o servidor MySQL seja iniciado completamente
        sleep 10
        mysql -h 127.0.0.1 -P 3306 -u dafws -p7rVQW48ph2 -e "SHOW DATABASES;"
